chat:
  use-group-format: false
  # Global format (use only if the above option is false)
  format: "%tchat_prefix% &a%player% &e>> &f%message%"
  # This option is used to display on the console the messages from the players
  register-messages-on-console: true
