main: minealex.tchat.TChat
version: 4.0.0-DEV-4
name: TChat
author: Mine_Alex
api-version: 1.13

depend: [PlaceholderAPI]

commands:
  tchat:
    description: Reload the plugin
    usage: /<command> <reload|version>
    aliases:
      - chat
  chatcolor:
    description: Open's the chatcolor menu
    usage: /<command>
    aliases:
      - cc


permissions:
  tchat.chatcolor.menu:
    description: Permission to open the chatcolor menu
    default: false