main: minealex.tchat.TChat
version: 4.0.0-DEV-1
name: TChat
author: Mine_Alex
api-version: 1.13

depend: [PlaceholderAPI]

commands:
  tchat:
    description: Reload the plugin
    usage: /<command> <reload|version>
    permission: tchat.admin
    aliases:
      - chat